#!/bin/bash

_script="$(readlink -f ${BASH_SOURCE[0]})"
_base="$(dirname $_script)"
_directory=$(basename $_base)

### Usage ###

#alias torified="ssh -L 8118:127.0.0.1:8118 -L 8123:127.0.0.1:8123 <username>@<ip> -p 2222"
# Note: tor: 8118 -> 9050, proxy: 8123

### Configuration ###

# folder name
_DOCKER_IMAGE=$(echo $_directory| tr '[:upper:]' '[:lower:]')
_DOCKER_CONTAINER="$_DOCKER_IMAGE"_container

### Entry Point ###

docker_process() {
  local _host=$(hostname)
  local _uid=$UID
  # (used for port redirect)
  local _ports="-p 2222:22"

  $_DOCKER rm $_DOCKER_CONTAINER > /dev/null 2>&1
  _DOCKER_PID=$($_DOCKER run --detach --tty --net=host --hostname="$_host" --user="$_uid" --publish-all $_ports --name $_DOCKER_CONTAINER $_DOCKER_IMAGE "/usr/bin/supervisord")
}

source ./Dockercommand $_DOCKER_IMAGE $_DOCKER_CONTAINER $@

exit
