#!/bin/bash

_script="$(readlink -f ${BASH_SOURCE[0]})"
_base="$(dirname $_script)"
_directory=$(basename $_base)

### Usage ###

#alias torified="ssh -L 8118:127.0.0.1:8118 -L 8123:127.0.0.1:8123 <username>@<ip> -p 2222"
# Note: tor: 8118 -> 9050, proxy: 8123

### Configuration ###
_DOCKER_IMAGE=$(echo $_directory | tr '[:upper:]' '[:lower:]')
_DOCKER_CONTAINER="$_DOCKER_IMAGE"_container

### Entry Point ###

docker_process() {
  local _host=$(hostname)
  local _uid=$UID
  # (used for port redirect)
  local _ports="-p 2222:22"

  # entry point (i.e. startup operation)
  local _execute=/usr/bin/supervisord

  _DOCKER_PID=$($_DOCKER run --detach --tty --net=host --restart=always --hostname="$_host" --publish-all $_ports --name $_DOCKER_CONTAINER $_DOCKER_IMAGE "$_execute" )
}

source $_base/Dockercommand $_DOCKER_IMAGE $_DOCKER_CONTAINER $@

exit
