#!/bin/bash

_script="$(readlink -f ${BASH_SOURCE[0]})"
_base="$(dirname $_script)"
_directory=$(basename $_base)

### Configuration ###

# folder name
_DOCKER_IMAGE="$_directory"
_DOCKER_CONTAINER="$_DOCKER_IMAGE"_container

### Entry Point ###

docker_process() {
  # ports (tor, torDir, privoxy)
  local _ports="-p 8123:8123 -p 8118:8118 -p 9001:9001 -p 9030:9030 -p 2222:22"
  local _host=$(hostname)

  $_DOCKER rm $_DOCKER_CONTAINER > /dev/null 2>&1
  _DOCKER_PID=$($_DOCKER run -d -t --net=host -h $_host $_ports --name $_DOCKER_CONTAINER $_DOCKER_IMAGE "/usr/bin/supervisord")

  # alias torified="ssh -L 8118:127.0.0.1:8118 <usernam>@<ip>-p 2222"
  # tor: 8118 -> 9050
  # proxy: 8123
}

source ./DockerCommand $@

exit
